// <auto-generated />
using CityInfo.api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.api.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("CityInfo.api.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "i hate it ",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 2,
                            Description = "i hate it ",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 3,
                            Description = "i hate it ",
                            Name = "tripoli York"
                        },
                        new
                        {
                            Id = 4,
                            Description = "i hate it ",
                            Name = "bengazi York"
                        },
                        new
                        {
                            Id = 5,
                            Description = "i hate it ",
                            Name = "York"
                        });
                });

            modelBuilder.Entity("CityInfo.api.Entities.PointOfInrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInrest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "blaalala",
                            Name = "Central park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "blaalala",
                            Name = "Central park"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Description = "blaalala",
                            Name = "Central park"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Description = "blaalala",
                            Name = "Central park"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Description = "blaalala",
                            Name = "Central park"
                        });
                });

            modelBuilder.Entity("CityInfo.api.Entities.PointOfInrest", b =>
                {
                    b.HasOne("CityInfo.api.Entities.City", "City")
                        .WithMany("pointOfInrests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.api.Entities.City", b =>
                {
                    b.Navigation("pointOfInrests");
                });
#pragma warning restore 612, 618
        }
    }
}
